export const SET_FILTER_VALUE = "COLLECTION/SET_FILTER";
export const CLEAR_FILTER = "COLLECTION/CLEAR_FILTER";

export const SET_SEARCH_QUERY = "COLLECTION/SET_SEARCH_QUERY";
export const CLEAR_SEARCH = "COLLECTION/CLEAR_SEARCH";

export const SET_SELECTED_ITEMS = "COLLECTION/SET_SELECTED_ITEMS";
export const SET_SORT = "COLLECTION/SET_SORT";
